### ISSUE TITLE
ModAudio not working on Android 6

### ISSUE THREAD

**Issue by TheNetStriker** [C3C0/GravityBox#362]
ModAudio.java does not work any more on Android 6. I found out that the Class android.media.AudioService was moved to com.android.server.audio.AudioService. Also the RemotePlaybackState class doesn't seam to exist any more. I now simply set the build.prop property "ro.config.media_vol_steps" to 32 steps to get more volume steps. Can you please also implement this in your app?

**Comment by C3C0** [comment]
This is not an official repository. The official one can be found here: https://github.com/GravityBox/GravityBox
There are 4 branches, each for major Android version. ModAudio works fine. Well, at least on supported devices.
